---
- name: 'Install apt apps'
  sudo: no
  apt: pkg={{ item }}
  when: ansible_os_family == "Debian"
  with_items:
    - curl
    - tmux
    - vim
    - zsh
    - imagemagick
    - openssl
    - python
    - redis-server
    - tree
    - nodejs
    - htop
    - sqlite
    - docker
    - wget
