---
- name: 'Install oh my zsh'
  git:
    repo: "{{ ohmyzsh_repo }}"
    dest: "{{ ohmyzsh_repo_local_destination }}"

- name: 'Install git in debian'
  apt: pkg=zsh
  when: ansible_os_family == "Debian"
