---
# - name: 'Install configs sublime'
#   git:
#     repo: "{{ sublime_repo }}"
#     dest: "{{ sublime_repo_local_destination }}"
#   sudo: no

- name: Check sublime config directory
  stat: path={{ sublime_repo_local_destination }}
  register: sublime_config_exist

- name: Update sublime configs
  shell: cd {{ sublime_repo_local_destination }} && git pull origin master
  ignore_errors: True
