---
- name: 'Install rbenv with brew'
  sudo: no
  homebrew: name={{ item }} state=present
  when: ansible_os_family == "Darwin"
  with_items:
    - rbenv
    - ruby-build

- name: 'Install rbenv for linux'
  git:
    repo: "{{ rbenv_repo }}"
    dest: "{{ rbenv_repo_local_destination }}"
  sudo: no
  when: ansible_os_family == "Debian"
