---
- name: Brew is available?
  command: brew --version
  register: brew_available
  ignore_errors: True
  changed_when: false

- name: 'Update homebrew'
  homebrew:
    update_homebrew: yes
  when: ansible_os_family == "Darwin"

- name: 'Install brew apps'
  homebrew: name={{ item }} state=present
  when: ansible_os_family == "Darwin"
  with_items:
    - tmux
    - freetype
    - imagemagick
    - jpeg
    - openssl
    - python
    - tree
    - htop-osx
    - wget
