---
- name: 'Update brew cask'
  shell: brew update

- name: 'Installing default Apps'
  homebrew_cask: name={{item}} state=present
  with_items:
    - alfred
    - firefox
    - iterm2
    - vlc
    - sourcetree
