---
- name: 'Installing Homebrewcask'
  sudo: no
  shell: brew install caskroom/cask/brew-cask

- name: 'Update brew cask'
  sudo: no
  shell: brew-cask update

- name: 'Installing default Apps'
  sudo: no
  homebrew_cask: name={{item}} state=present
  with_items:
    - bartender
    - adium
    - alfred
    - bartender
    - cyberduck
    - evernote
    - firefox
    - google-chrome
    - iterm2
    - vlc
